### ISSUE TITLE
Cif to pdb and/or xyz conversion

### ISSUE THREAD

**Issue by ashkurti** [richardjgowers/MDAnalysis_CIFReading#1]
Hi Richard,

Does this conversion account for all symmetries specified in a cif file.

In several forums I have read for people complaining on cases when OpenBabel mishandles the symmetries. 

Thanks,

Ardita

**Comment by richardjgowers** [comment]
Hey Ardita

I've updated this repo with an example cif file which I've used successfully.  

This all just uses openbabel to do the unpacking, so any bugs in that will also be a bug here.  According to the [release notes (ctrl+F for FillUnitCell)](https://media.readthedocs.org/pdf/open-babel/latest/open-babel.pdf) @patrickfuller improved FillUnitCell in openbabel in v2.4 in Sept '16, so maybe it's been fixed since those posts?  It seemed to work for me for this case, but obviously check what it makes for you.

Hope that helps!
